### ISSUE TITLE
[REQUEST]: Choose a embbeder manually,not always hubert.

### ISSUE THREAD

**Issue by hpx502766238** [deiteris/voice-changer#171]
### In a few words, describe your idea

To get better effect,I want to choose the contentvec embbeder in webpage.

**Comment by deiteris** [comment]
Hi @hpx502766238! RVC uses contentvec embedder and most of the models are trained with contentvec. `hubert_base` is just a wrong name of the embedder, it is not a Facebook HuBERT model.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/2121
