### ISSUE TITLE
[REQUEST]: add zluda support for amd gpu

### ISSUE THREAD

**Issue by vermiona** [deiteris/voice-changer#178]
### In a few words, describe your idea

ZLUDA helps bridge the gap between NVIDIA's CUDA ecosystem and amd's GPU hardware, making cross-platform GPU computing more accessible. in this case voice-changer apps, thanks.

**Comment by deiteris** [comment]
Hi @vermiona, ZLUDA support most likely will not be introduced. The current version heavily relies on onnxruntime which doesn't work with ZLUDA, unless recompiled without cuDNN support. Current DirectML version has performance comparable to ROCm, and as soon as ROCm gains more traction with WSL, this will be a better option.

**Comment by vermiona** [comment]
> Hi @vermiona, ZLUDA support most likely will not be introduced. The current version heavily relies on onnxruntime which doesn't work with ZLUDA, unless recompiled without cuDNN support. Current DirectML version has performance comparable to ROCm, and as soon as ROCm gains more traction with WSL, this will be a better option.

ah i see, Thank you for sharing such valuable insights!😁
