### ISSUE TITLE
[REQUEST]: Ability to change host address for prebuilt .exe

### ISSUE THREAD

**Issue by Weroxig** [deiteris/voice-changer#182]
### In a few words, describe your idea

It looks like changing the host is possible when running from source but not from the prebuild releases. It would be nice if this could be added to the prebuilts too, as a cli flag or something

**Comment by deiteris** [comment]
Hi @Weroxig, it is possible with `.env` file.
https://github.com/deiteris/voice-changer/issues/180#issuecomment-2359166278
