### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by Deafilamor** [deiteris/voice-changer#184]
### Voice Changer Version

B23O9

### Operational System

Windows 10

### GPU

NVIDIA RTX 3090

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Nothing inside of software is an wrong its just so happens that for some reason Bitdefender flagged the MMVC.exe which starts the program as an Cloud threat . Is something in the voice changer that raises suspicion in an antivirus . Must be the cloud aplication into an web browser but wondering why it did flag it and remove it .

Just question will delete the issue comment once heard from you what can cause it.

### Application Screenshot

![obrázok_2024-10-20_203226012](https://github.com/user-attachments/assets/b36e9c76-220d-409b-bad7-97fe4bd31320)

### Logs on console

..

**Comment by Deafilamor** [comment]
![obrázok_2024-10-20_212935341](https://github.com/user-attachments/assets/22ba319f-e016-4350-b7d8-5611d8fdd0bc)

**Comment by deiteris** [comment]
Hi @Deafilamor, the voice changer is packed with PyInstaller which often causes a false positive detection. It might be that there's some generic pattern that trips BitDefender detection (for example, the app is bundled with default PyInstaller icon), I could try check this out.

**Comment by Deafilamor** [comment]
What about just making it be an different app icon ? like custom one or something ? since i really dont know it happend only recently without any updates on your side. So immidiently thought it was Bitdefender just wasnt sure and it stuck me on the ones so i needed to downgrade to b2245 and it stopped atleast on that versions others are still breaking the antivirus

**Comment by deiteris** [comment]
I've updated the executable to include the icon and BitDefender doesn't seem to be triggered anymore according to VirusTotal. There are still several false positives however.
https://www.virustotal.com/gui/file-analysis/ZjlhZjAwMmQ5Yjg3ZGNhN2IyY2JjOTE0MmIwZmNkNjU6MTczMzU4ODE1OQ==

**Comment by Deafilamor** [comment]
so now it shouldnt be posting an bitdefender error ? let me try

**Comment by Deafilamor** [comment]
Before closing , thanks for fixing this small yet weird issue with the antivirus . Everything loaded and no alarms by bitdefender were started so its going great now :D . Thanks again
